# Perfil producción con base de datos en Docker
spring:
  datasource:
    url: jdbc:mysql://mysql-prod:3306/estudiantesdb_prod
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect